#!/usr/bin/env bash
# This script prepares default Poky environment for Yocto builds

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/zxsettings

echo "-----------------------------------------------------------------------"
echo Setting up environment...
echo "-----------------------------------------------------------------------"

cd ${ROOT_DIR}
source ${ENV_SOURCE}
