name: CI
on: [push]

jobs:
  build_dk2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Manifest
      run: |
        make manifest force
    - name: Build image
      run: |
        make build_image_dk2
